### ISSUE TITLE
Refresh breaks node stream, causes connection refused error

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/starlog#11]
Going to `localhost:8082` redirects to `http://localhost:8082/#!/home` and displays the site. However, on refresh, the connection is refused and the server throws an error. 

``` sh
11:11 ~/src/starlog $ npm run serve

> starlog@0.0.0 serve /Users/richard/src/starlog
> node serve.js

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/richard/.nvm/versions/node/v0.12.0/bin/node" "/Users/richard/.nvm/versions/node/v0.12.0/bin/npm" "run" "serve"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! starlog@0.0.0 serve: `node serve.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starlog@0.0.0 serve script 'node serve.js'.
npm ERR! This is most likely a problem with the starlog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node serve.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls starlog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/richard/src/starlog/npm-debug.log
```

As well, this is logged in the browser, although I am not sure what it means or if it is relevant:

```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

**Comment by krl** [comment]
This is the connection to ipfs api failing, it should not happen if you have the right API_ORIGIN set

**Comment by RichardLitt** [comment]
No longer a problem if _actually running the_ daemon. Note, future users!
